### ISSUE TITLE
4.0.6 - Arduino --> VSCode and PlatformIO

### ISSUE THREAD

**Issue by pesor** [pesor/TTGO-T-HIGrow#7]
@ericsebastion **WROTE**

> just purchased the BME280 version and i cant find where to download the arduino file for this new 4.x version I was redirected to. I used the old version and the soil part shows up as working in the serial monitor but the mqtt wont connect and I don't see the temp and humid readings. Any help would be appreciated. I'm trying to use this in Home Assistant also if that helps clarify.

**Comment by pesor** [comment]
I did abandon the Arduino EDI for practical reasons.

I have changed to VSCode and PlatformIO, as this platform is much easier to maintain, and do development in.

You will have to install VSCode and PlatformIO, in order to run version 4.x.x.

On YouTube there is very good instructions on how to do this, just search for VSCode and PlatformIO, and it should go very easy to install it, and after it is installed, it is like using any text editor, this is just preperet for C++, and it is very easy to compile and get the programs to the module.

Don't hesitate to ask questions in this thread, I will answer fast.

**Comment by pesor** [comment]
@BeardedTinker 

Maybe it is soon time for a video for the 4.x.x installation, with an inclusion for the VSCode and PlatformIO

;-)

**Comment by pesor** [comment]
I came by this video, it is about 3D firmware update, but there are a chapter where he explains how to install VSCode, and another chapter for the PlatformIO.

All the rest you just skip.

https://www.youtube.com/watch?v=eq_ygvHF29I

**Comment by BeardedTinker** [comment]
> @BeardedTinker
> 
> Maybe it is soon time for a video for the 4.x.x installation, with an inclusion for the VSCode and PlatformIO

It's overdue already! I hope, if all goes as planed, to have it done in first week of February. Kids should be back in school then (real not online) and I'll have a bit more time then. 
I'm really guilty for this one 😁

**Comment by ericsebastion** [comment]
@BeardedTinker looking forward to it!

**Comment by elecoq129** [comment]
If I may a comment to BeardeTinker, as there is a large of o tuto for installing VSCode/PlattformIO (https://randomnerdtutorials.com/vs-code-platformio-ide-esp32-esp8266-arduino/) I would rather prefer you'll work on a tuto to install the necessary stuff (Eric + Python) in order to run the Autodiscovery part. That would me usuful!
It's just an idea...
